# Generated by Django 4.2.7 on 2023-12-20 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='ename',
        ),
    ]
